version: '3.0'
services:
  SVCDB31:
    container_name: svcdb31-container
    image: mongo:4
    restart: always
    networks:
      - net-coplandpost
    volumes:
      - ./data-storage:/data/db
    ports:
      - "27031:27017"

  FRAUD:
    container_name: fraud-container
    restart: always
    image: node:16
    working_dir: /usr/src/app
    command: bash -c "npx nodemon main/server.js"
    environment:
      - MONGO_URI=SVCDB31
      - HTTP_PORT=5092
    networks:
      - net-coplandpost
    volumes: 
      - ./dist:/usr/src/app
      - ./package.json:/usr/src/app/package.json
    ports: 
      - "5092:5092"
    links:
      - SVCDB31

networks:
  net-coplandpost:
    external:
      name: coplandpost-network
